services:
  api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: garagge-db
      POSTGRES_USER: admin0
      POSTGRES_PASSWORD: passw0rd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
        
volumes:
  db-data: