services:
  server:
    build:
      context: ./server
      dockerfile: ./src/Api/Dockerfile
      target: final-no-frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=db
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - server

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80