name: garagge

services:
  server:
    container_name: server
    image: ghcr.io/jacup/garagge:latest
    ports:
      - "5000:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      # Use named volume for better cross-platform compatibility
      - garagge-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

volumes:
  garagge-db-data:
